#!/bin/sh 
##
# "Copyright (c) 2006 University of Southern California.
# All rights reserved.
#
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose, without fee, and without written
# agreement is hereby granted, provided that the above copyright
# notice, the following two paragraphs and the author appear in all
# copies of this software.
#
# IN NO EVENT SHALL THE UNIVERSITY OF SOUTHERN CALIFORNIA BE LIABLE TO
# ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
# DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
# DOCUMENTATION, EVEN IF THE UNIVERSITY OF SOUTHERN CALIFORNIA HAS BEEN
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# THE UNIVERSITY OF SOUTHERN CALIFORNIA SPECIFICALLY DISCLAIMS ANY
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE
# PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
# SOUTHERN CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE,
# SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
#
##

##
# BaseStation progmming script
#
# Authors: Ki-Young Jang
# Embedded Networks Laboratory, University of Southern California
# Modified: 2/6/2007
##

TOOLS_DIR="$TENET_ROOT/tools/programming"
PROGRAM="BaseStation"
IMG_NAME="main.ihex"
IMG_PATH_EXT=""

JOB="Program"
MOTE_TYPE="telosb"
MOTE_ID=""
MOTE_ADDR=""

ShowUsage()
{
	echo "----------------------------------------------------------------------"
	echo " install_Tenet <MOTE_TYPE> <DEVICE> <TOS_ADDR>"
	echo "----------------------------------------------------------------------"
    echo "  <MOTE_TYPE>: telosb (default), micaz, mica2 or mica2dot"
	echo "  <DEVICE>   : set the device"
	exit 1
}

if [ "$1" = "" ]
then
  ShowUsage 
fi

if [ "$TENET_ROOT" = "" ]
then
    echo "TENET_ROOT not found"
    exit 1
fi

if [ "$TENET_HOST_OS" = "" ]
then
    echo "TENET_HOST_OS not found"
    exit 1
fi

if [ $# -ne 3 ]
then
	ShowUsage
fi

MOTE_TYPE=$1
MOTE_DEV=$2
MOTE_ADDR=$3
	
case $JOB in

    "Program")

        case $MOTE_TYPE in

            "telosb")
                IMG_PATH="$TENET_ROOT/mote/apps/$PROGRAM/build/telosb"
                $TOOLS_DIR/install_mote $MOTE_TYPE $IMG_PATH $MOTE_DEV $MOTE_ADDR
                ;;        
 
            "micaz"|"mica2"|"mica2dot")
                IMG_PATH="$TENET_ROOT/mote/apps/$PROGRAM/build/micaz"
                $TOOLS_DIR/install_mote $MOTE_TYPE $IMG_PATH $MOTE_DEV $MOTE_ADDR
                ;;

            *)
                echo "[ERROR] $MOTE_TYPE is not supported"
                ShowUsage
                ;;
            esac                
        ;;
esac

exit 0
