/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *frame1;
  GtkWidget *fixed2;
  GtkWidget *drawingarea1;
  GtkWidget *label1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *button1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *button3;
  GtkWidget *button2;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, 740, 630);
  gtk_window_set_title (GTK_WINDOW (window1), "Particle Filter");

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_fixed_put (GTK_FIXED (fixed1), frame1, 8, 8);
  gtk_widget_set_size_request (frame1, 720, 525);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (frame1), fixed2);

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea1);
  gtk_fixed_put (GTK_FIXED (fixed2), drawingarea1, 8, 0);
  gtk_widget_set_size_request (drawingarea1, 700, 500);

  label1 = gtk_label_new ("Map");
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 8, 592);
  gtk_widget_set_size_request (entry1, 104, 24);
  gtk_entry_set_text (GTK_ENTRY (entry1), "localhost");

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 120, 592);
  gtk_widget_set_size_request (entry2, 112, 24);
  gtk_entry_set_text (GTK_ENTRY (entry2), "rth.map");

  button1 = gtk_button_new_with_mnemonic ("Connect");
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 8, 544);
  gtk_widget_set_size_request (button1, 64, 24);

  label2 = gtk_label_new ("Host");
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 8, 576);
  gtk_widget_set_size_request (label2, 37, 16);

  label3 = gtk_label_new ("Map file");
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 120, 576);
  gtk_widget_set_size_request (label3, 56, 16);

  button3 = gtk_button_new_with_mnemonic ("Run");
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 88, 544);
  gtk_widget_set_size_request (button3, 64, 24);

  button2 = gtk_button_new_with_mnemonic ("Quit");
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 168, 544);
  gtk_widget_set_size_request (button2, 64, 24);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, drawingarea1, "drawingarea1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");

  return window1;
}

