/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "run.h"

int gui;

int
main (int argc, char *argv[])
{
  GtkWidget *window1;

	g_thread_init (NULL);
	gdk_threads_init();

	if ((argc > 1) && (argv[1][0]=='g'))
		gui=1;
	else
		gui=0;

	if (!gui)
		run_pf();
	else
		{
	  gtk_set_locale ();
	  gtk_init (&argc, &argv);

	  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

	  window1 = create_window1 ();
	  gtk_widget_show (window1);

		gdk_threads_enter();
	  gtk_main ();
		gdk_threads_leave();
		}

  return 0;
}

